spring.application.name=sanjeeswaran-mart

spring.datasource.url=jdbc:postgresql://${dpg-dao0vj0ae00c73aclua0-a}:${5432}/${sanjeeswaran_mart_db}
spring.datasource.username=${sanjeeswaran_mart_db_user}
spring.datasource.password=${fTePMqqQST5bTS1n11HtxHshG7HNLspn}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}